[package]
name = "side"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0-beta.1"
lazy_static = "1.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
csv = "1.1"